#!/bin/bash
echo "nvcc: NVIDIA (R) Cuda compiler driver"
echo "Copyright (c) 2005-2022 NVIDIA Corporation"
echo "Built on Mon_Oct_24_19:12:58_PDT_2022"
echo "Cuda compilation tools, release 12.0, V12.0.76"
echo "Build cuda_12.0.r12.0/compiler.31968024_0"
